name: IMDb Pipeline

on:
  workflow_dispatch:

jobs:
  imdb:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: imdb
          POSTGRES_PASSWORD: imdb
          POSTGRES_DB: imdb
        options: >-
          --health-cmd="pg_isready -U imdb -d imdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends wget curl postgresql-client gzip
          sudo rm -rf /var/lib/apt/lists/*

      - name: Initialize Schema
        run: psql -h localhost -U imdb -d imdb -f ./src/main/resources/db/migration/V1__Initial_Schema.sql
        env:
          PGPASSWORD: imdb

      - name: Load IMDb data directly into Postgres
        run: |
          mkdir -p data
          for file in name.basics title.akas title.basics title.crew title.episode title.principals title.ratings; do
          tbl=$(basename "$file" .tsv | tr '.' '_')
          echo "📊 Downloading and loading $tbl..."
          
          # Download and unzip
          wget -q "https://datasets.imdbws.com/$file.tsv.gz" -O "data/$file.tsv.gz"
          gunzip -f "data/$file.tsv.gz"
          
          # Check if table exists
          table_exists=$(psql -h localhost -U imdb -d imdb -tAc "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='$tbl');")
          if [ "$table_exists" = "t" ]; then
          # Truncate table to avoid duplicates
          psql -h localhost -U imdb -d imdb -c "TRUNCATE TABLE $tbl;"
          
          # Load data
          psql -h localhost -U imdb -d imdb -c "\COPY $tbl FROM 'data/$file.tsv' WITH (FORMAT text, DELIMITER E'\t', NULL '\N', HEADER true)"
          echo "✅ $tbl loaded successfully."
          else
          echo "⚠️ Table $tbl does not exist, skipping."
          fi
          
          # Delete file to save space
          rm -f "data/$file.tsv"
          echo "🗑 File deleted: $file.tsv"
          done
        env:
          PGPASSWORD: imdb

      - name: Analyze tables
        run: |
          psql -h localhost -U imdb -d imdb -c "VACUUM ANALYZE;"
        env:
          PGPASSWORD: imdb

      - name: Build and run API
        run: |
          mvn -B package --file pom.xml -DskipTests
          nohup mvn spring-boot:run > /tmp/app.log 2>&1 &
          echo "⏳ Waiting for API to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/api/movies/health | grep -q "UP"; then
              echo "✅ API is up!"
              break
            fi
            sleep 2
          done
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/imdb
          SPRING_DATASOURCE_USERNAME: imdb
          SPRING_DATASOURCE_PASSWORD: imdb
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}

      - name: Run API smoke tests
        run: |
          echo "🔍 Health Check"
          curl -f http://localhost:8080/api/movies/health

          echo "🎬 Search by title"
          curl -f "http://localhost:8080/api/movies?title=inception&page=0&size=5"

          echo "🎬 Get movie details"
          curl -f "http://localhost:8080/api/movies/tt1375666"

          echo "⭐ Get top-rated movies"
          curl -f "http://localhost:8080/api/movies/top?limit=10"

          echo "🤖 Start recommendation session"
          curl -f -X POST "http://localhost:8080/api/movies/suggest/start" \
            -H "Content-Type: application/json" \
            -d '{"query": "Christopher Nolan movies"}'

          echo "📝 Submit feedback"
          curl -f -X POST "http://localhost:8080/api/movies/suggest/feedback" \
            -H "Content-Type: application/json" \
            -d '{
              "userId": "user123",
              "sessionId": "sess_abc123",
              "movieId": "tt1375666",
              "liked": true,
              "rating": 5
            }'

          echo "🎯 Get recommendations"
          curl -f "http://localhost:8080/api/movies/suggest/user123"
